### ISSUE TITLE
Рекомендация:

### ISSUE THREAD

**Issue by Muxamedin** [OleksandrLozinskyy/Hillel_Python_Lessons#3]
https://github.com/OleksandrLozinskyy/Hillel_Python_Lessons/blob/eb050d445c023842a8cab497f9adb9dcc4dc7f02/Lesson4/same_numbers_rand.py#L10

Так как мы не проходили ни списки(list) ни наборы (set) рекомендую подумать (на досуге) как решить эту задачу посредством методов строки 
Например: 
       .count()
       .find()

**Comment by OleksandrLozinskyy** [comment]
Добавлено решение без использования списков и сетов.
