### ISSUE TITLE
isdigit() - проверяет  что в строке числа от 0 и больше 

### ISSUE THREAD

**Issue by Muxamedin** [OleksandrLozinskyy/Hillel_Python_Lessons#4]
https://github.com/OleksandrLozinskyy/Hillel_Python_Lessons/blob/64d1a2f7a372cf6c4d3cb986cd7a98ec4449526a/Lesson5/number_piramid.py#L2
isdigit() - проверяет  что в строке числа от 0 и больше 
поэтому когда вводим отрицательные числа приложение говорит о том что введено не число 
Та же ситуация и в первой задаче

**Comment by OleksandrLozinskyy** [comment]
Добавил проверки на отрицательные, дробные и отрицательные дробные числа.
