### ISSUE TITLE
Название верно но есть. не используется то что ожидается 

### ISSUE THREAD

**Issue by Muxamedin** [OleksandrLozinskyy/Hillel_Python_Lessons#5]
сколько чисел содержится одновременно как в первом списке
 так и втором 
 тоесть - сколько их чисел и там и там одинаковых (нужен не подсчет а пересечение )
    
https://github.com/OleksandrLozinskyy/Hillel_Python_Lessons/blob/6311ac3829a165b62ff1e9a20c51283e7d5255b2/Lesson7/sets_intersect.py#L32

**Comment by OleksandrLozinskyy** [comment]
Исправлено! Спасибо за замечание
